<?php

/**
 * @file
 * Provides a Collection View.
 */


/**
 * Implements hook_views_api().
 */
function islandora_solr_collection_view_views_api() {
  return array(
    'api' => '3.0',
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */

function islandora_solr_collection_view_islandora_collectionCModel_islandora_view_object(AbstractObject $object) {
  $view = views_embed_view('collection', 'block_1');
  $view = render($view);
  return array(
    'collection_view' => $view,
  );
}