<?php

/**
 * @file
 * Provides a Collection View.
 */

define('ISLANDORA_SOLR_COLLECTION_VIEW_DEFAULT_VIEW', 'collection');
define('ISLANDORA_SOLR_COLLECTION_VIEW_DEFAULT_DISPLAY', 'block');


/**
 * Implements hook_views_api().
 */
function islandora_solr_collection_view_views_api() {
  return array(
    'api' => '3.0',
  );
}

/**
 * Implements hook_menu(),
 */
function islandora_solr_collection_view_menu() {
  $items = array(
    'admin/islandora/tools/collection_view' => array(
      'title'            => 'Collection view',
      'description'      => 'Configuration page for collection view',
      'page callback'    => 'drupal_get_form',
      'page arguments'   => array('islandora_solr_collection_view_admin'),
      'file'             => 'includes/admin.inc',
      'access arguments' => array('administer site configuration'),
      'type'             => MENU_NORMAL_ITEM,
      'weight'           => -1,
    ),
  );

  return($items);
}

/**
 * Implements hook_theme().
 */
function islandora_solr_collection_view_theme() {
  $path = drupal_get_path('module', 'islandora_solr_collection_view');
  $file = 'theme.inc';

  return array(
    'islandora_solr_teaser' => array(
      'path' => $path . '/theme',
      'file' => $file,
      'template' => 'islandora-solr-teaser',
      'variables' => array(
        'values' => array(),
      ),
    ),
  );
  // Results page.

}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */

function islandora_solr_collection_view_islandora_collectionCModel_islandora_view_object(AbstractObject $object) {
  // TODO: render the block so that it has contextual menus.
  $view = views_embed_view('collection', 'block', 'info:fedora/' . $object->id);
  $view = render($view);
  return array(
    'collection_view' => $view,
  );
}
